# Generated by Django 5.1.4 on 2024-12-12 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(default='None', max_length=30)),
                ('last_name', models.CharField(blank=True, default='None', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('role', models.CharField(blank=True, choices=[('Driver', 'Driver'), ('Passenger', 'Passenger')], default='Passenger', max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('addressLat', models.FloatField(blank=True, null=True)),
                ('addressLng', models.FloatField(blank=True, null=True)),
                ('government_id_type', models.CharField(blank=True, choices=[('SSN', 'Social Security Number'), ("Driver's License", "Driver's License"), ('Passport', 'Passport')], max_length=50, null=True)),
                ('government_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('terms_and_conditions_accepted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
