# Generated by Django 5.1.4 on 2024-12-12 14:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('going_from', models.CharField(max_length=255)),
                ('going_to', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ride_description', models.TextField(blank=True, null=True)),
                ('going_from_lat', models.FloatField(blank=True, null=True)),
                ('going_from_lng', models.FloatField(blank=True, null=True)),
                ('going_to_lat', models.FloatField(blank=True, null=True)),
                ('going_to_lng', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('range_in_km', models.FloatField(default=0.0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driven_rides', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='vehicle.vehicle')),
            ],
        ),
    ]
